server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-management?serverTimezone=GMT%2b8 #\u5317\u4EAC\u65F6\u533A
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml